version: "3.9"

services:
  bookstoreimage:
    build: .
    # always restart the container if it stops or fails
    restart: always
    depends_on:
      - db
    image: mysql:5.7
    ports:
      - "80:80"
    # environment is optional for this section
    environment:
      MYSQL_ROOT_PASSWORD: a1234
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_USER: clarusway 
      MYSQL_DATABASE_PASSWORD: Clarusway_1
      MYSQL_DATABASE_DB: bookstore_db
      MYSQL_DATABASE_PORT: 3306
    networks:
      - bookstoreNet

  redis:
    image: redis:latest
    # always restart the container if it stops or fails
    restart: always



  db:
    image: mysql:5.7
    # always restart the container if it stops or fails
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a1234
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
      MYSQL_DATABASE: bookstore_db
    networks:
      - bookstoreNet

networks:
  bookstoreNet:
    # driver: bridge

